<a href="https://colab.research.google.com/github/Nada-Desoki/Bank-Customer-Churn-Credit-Analysis/blob/main/Bank_Churn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel('Bank Data.xlsx')

In [5]:
cust = pd.read_excel('Bank Data.xlsx', sheet_name='Customer_Info')
acc = pd.read_excel('Bank Data.xlsx', sheet_name='Account_Activity')
trans = pd.read_excel('Bank Data.xlsx', sheet_name='Transaction_Credit')

In [6]:
df = pd.merge(cust, acc, on='Customer_ID')
df = pd.merge(df, trans, on='Customer_ID')

In [7]:
print(df.columns)

Index(['Customer_ID', 'Churn_Status', 'Age', 'Gender', 'Num_Dependents',
       'Education_Level', 'Marital_Status', 'Income_Range', 'Card_Type',
       'Tenure_Months', 'Num_Bank_Products', 'Inactive_Months_Last_Year',
       'Customer_Service_Calls', 'Credit_Limit', 'Revolving_Balance',
       'Available_Credit', 'Spending_Change_Q4_Q1', 'Total_Transaction_Amount',
       'Total_Transaction_Count', 'Transaction_Count_Change_Q4_Q1',
       'Credit_Utilization_Ratio'],
      dtype='object')

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df["Marital_Status"] = df["Marital_Status"].str.strip()

In [10]:
df["Marital_Status"] = df["Marital_Status"].str.title()

In [11]:
df["Marital_Status"] = df["Marital_Status"].replace({"Marrid":"Married", "Sngle":"Single", "Dvorced":"Divorced"})

In [12]:
df.replace("Unknown", np.nan, inplace=True)

df["Age"] = df["Age"].fillna(df["Age"].median())
df["Inactive_Months_Last_Year"] = df["Inactive_Months_Last_Year"].fillna(df["Inactive_Months_Last_Year"].median())
df["Education_Level"] = df["Education_Level"].fillna(df["Education_Level"].mode()[0])
df["Marital_Status"] = df["Marital_Status"].fillna(df["Marital_Status"].mode()[0])
df["Income_Range"] = df["Income_Range"].fillna(df["Income_Range"].mode()[0])

/tmp/ipykernel_46015/3736302472.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("Unknown", np.nan, inplace=True)

In [13]:
df["Education_Level"]

0        High School
1           Graduate
3           Graduate
5        High School
6         Uneducated
            ...
10124       Graduate
10125       Graduate
10126    High School
10127       Graduate
10128       Graduate
Name: Education_Level, Length: 10127, dtype: object

In [14]:
df["Education_Level"]=='Unknown'

0        False
1        False
3        False
5        False
6        False
         ...
10124    False
10125    False
10126    False
10127    False
10128    False
Name: Education_Level, Length: 10127, dtype: bool

In [15]:
print(df["Marital_Status"].head(20))

0     Married
1      Single
3     Married
5     Married
6     Married
7     Married
8     Married
9      Single
10     Single
11     Single
12    Married
13    Married
14     Single
15    Married
16    Married
17    Married
18     Single
19    Married
20    Married
21    Married
Name: Marital_Status, dtype: object

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10127 entries, 0 to 10128
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Customer_ID                     10127 non-null  int64
 1   Churn_Status                    10127 non-null  object
 2   Age                             10127 non-null  float64
 3   Gender                          10127 non-null  object
 4   Num_Dependents                  10127 non-null  int64
 5   Education_Level                 10127 non-null  object
 6   Marital_Status                  10127 non-null  object
 7   Income_Range                    10127 non-null  object
 8   Card_Type                       10127 non-null  object
 9   Tenure_Months                   10127 non-null  int64
 10  Num_Bank_Products               10127 non-null  int64
 11  Inactive_Months_Last_Year       10127 non-null  float64
 12  Customer_Service_Calls          10127 non-null  int64
 13  Credit_Limit                    10127 non-null  float64
 14  Revolving_Balance               10127 non-null  int64
 15  Available_Credit                10127 non-null  float64
 16  Spending_Change_Q4_Q1           10127 non-null  float64
 17  Total_Transaction_Amount        10127 non-null  int64
 18  Total_Transaction_Count         10127 non-null  int64
 19  Transaction_Count_Change_Q4_Q1  10127 non-null  float64
 20  Credit_Utilization_Ratio        10127 non-null  float64
dtypes: float64(7), int64(8), object(6)
memory usage: 1.7+ MB

In [17]:
numeric_cols = df.select_dtypes(include=['number']).columns

In [18]:
print(numeric_cols)

Index(['Customer_ID', 'Age', 'Num_Dependents', 'Tenure_Months',
       'Num_Bank_Products', 'Inactive_Months_Last_Year',
       'Customer_Service_Calls', 'Credit_Limit', 'Revolving_Balance',
       'Available_Credit', 'Spending_Change_Q4_Q1', 'Total_Transaction_Amount',
       'Total_Transaction_Count', 'Transaction_Count_Change_Q4_Q1',
       'Credit_Utilization_Ratio'],
      dtype='object')

In [19]:
print(df['Customer_ID'].unique())

[768805383 818770008 713982108 ... 716506083 717406983 714337233]

In [20]:
print(df['Customer_ID'].isnull().sum())

0

In [21]:
numeric_cols = df.select_dtypes(include=['number']).columns
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')
    df[col] = df[col].fillna(df[col].median())

In [22]:
print(df['Age'].head(20))

0     45.0
1     49.0
3     46.0
5     40.0
6     40.0
7     44.0
8     51.0
9     32.0
10    37.0
11    48.0
12    42.0
13    65.0
14    56.0
15    35.0
16    57.0
17    44.0
18    48.0
19    41.0
20    61.0
21    45.0
Name: Age, dtype: float64

In [23]:
df[numeric_cols].head(20)

,Customer_ID,Age,Num_Dependents,Tenure_Months,Num_Bank_Products,Inactive_Months_Last_Year,Customer_Service_Calls,Credit_Limit,Revolving_Balance,Available_Credit,Spending_Change_Q4_Q1,Total_Transaction_Amount,Total_Transaction_Count,Transaction_Count_Change_Q4_Q1,Credit_Utilization_Ratio
0,768805383,45.0,3,39,5,1.0,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,818770008,49.0,5,44,6,1.0,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
3,713982108,46.0,3,36,4,1.0,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
5,769911858,40.0,4,34,3,4.0,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
6,709106358,40.0,3,21,5,1.0,2,4716.0,0,4716.0,2.175,816,28,2.500,0.000
7,713061558,44.0,2,36,3,1.0,2,4010.0,1247,2763.0,1.376,1088,24,0.846,0.311
8,810347208,51.0,4,46,6,2.0,3,34516.0,2264,32252.0,1.975,1330,31,0.722,0.066
9,818906208,32.0,0,27,2,2.0,2,29081.0,1396,27685.0,2.204,1538,36,0.714,0.048
10,710930508,37.0,3,36,5,2.0,0,22352.0,2517,19835.0,3.355,1350,24,1.182,0.113
11,719661558,48.0,2,36,6,3.0,3,999999.0,1677,9979.0,1.524,1441,32,0.882,0.144
12,708790833,42.0,5,31,5,3.0,2,6748.0,1467,5281.0,0.831,1201,42,0.680,0.217
13,710821833,65.0,1,54,6,2.0,3,9095.0,1587,7508.0,1.433,1314,26,1.364,0.174
14,710599683,56.0,1,36,3,6.0,0,11751.0,0,11751.0,3.397,1539,17,3.250,0.000
15,816082233,35.0,3,30,5,1.0,3,8547.0,1666,6881.0,1.163,1311,33,2.000,0.195
16,712396908,57.0,2,48,5,2.0,2,2436.0,680,1756.0,1.190,1570,29,0.611,0.279
17,714885258,44.0,4,37,5,1.0,2,4234.0,972,3262.0,1.707,1348,27,1.700,0.230
18,709967358,48.0,4,36,6,2.0,3,30367.0,2362,28005.0,1.708,1671,27,0.929,0.078
19,753327333,41.0,3,34,4,4.0,1,13535.0,1291,12244.0,0.653,1028,21,1.625,0.095
20,806160108,61.0,1,56,2,2.0,3,3193.0,2517,676.0,1.831,1336,30,1.143,0.788
21,709327383,45.0,2,37,6,1.0,2,14470.0,1157,13313.0,0.966,1207,21,0.909,0.080

In [24]:
temp_df = pd.read_excel('Bank Data.xlsx', usecols=['Age'])
df['Age'] = temp_df['Age']

In [25]:
print(df['Age'].head(20))

0     45.0
1     49.0
3     40.0
5     44.0
6     51.0
7     32.0
8     37.0
9     48.0
10    42.0
11    65.0
12    56.0
13    35.0
14    57.0
15    44.0
16    48.0
17    41.0
18    61.0
19    45.0
20    47.0
21    62.0
Name: Age, dtype: float64

In [26]:
print(df['Customer_ID'].dtypes)

int64

In [27]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Age'] = df['Age'].astype(int)

In [28]:
df[numeric_cols].head(20)

,Customer_ID,Age,Num_Dependents,Tenure_Months,Num_Bank_Products,Inactive_Months_Last_Year,Customer_Service_Calls,Credit_Limit,Revolving_Balance,Available_Credit,Spending_Change_Q4_Q1,Total_Transaction_Amount,Total_Transaction_Count,Transaction_Count_Change_Q4_Q1,Credit_Utilization_Ratio
0,768805383,45,3,39,5,1.0,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,818770008,49,5,44,6,1.0,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
3,713982108,40,3,36,4,1.0,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
5,769911858,44,4,34,3,4.0,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
6,709106358,51,3,21,5,1.0,2,4716.0,0,4716.0,2.175,816,28,2.500,0.000
7,713061558,32,2,36,3,1.0,2,4010.0,1247,2763.0,1.376,1088,24,0.846,0.311
8,810347208,37,4,46,6,2.0,3,34516.0,2264,32252.0,1.975,1330,31,0.722,0.066
9,818906208,48,0,27,2,2.0,2,29081.0,1396,27685.0,2.204,1538,36,0.714,0.048
10,710930508,42,3,36,5,2.0,0,22352.0,2517,19835.0,3.355,1350,24,1.182,0.113
11,719661558,65,2,36,6,3.0,3,999999.0,1677,9979.0,1.524,1441,32,0.882,0.144
12,708790833,56,5,31,5,3.0,2,6748.0,1467,5281.0,0.831,1201,42,0.680,0.217
13,710821833,35,1,54,6,2.0,3,9095.0,1587,7508.0,1.433,1314,26,1.364,0.174
14,710599683,57,1,36,3,6.0,0,11751.0,0,11751.0,3.397,1539,17,3.250,0.000
15,816082233,44,3,30,5,1.0,3,8547.0,1666,6881.0,1.163,1311,33,2.000,0.195
16,712396908,48,2,48,5,2.0,2,2436.0,680,1756.0,1.190,1570,29,0.611,0.279
17,714885258,41,4,37,5,1.0,2,4234.0,972,3262.0,1.707,1348,27,1.700,0.230
18,709967358,61,4,36,6,2.0,3,30367.0,2362,28005.0,1.708,1671,27,0.929,0.078
19,753327333,45,3,34,4,4.0,1,13535.0,1291,12244.0,0.653,1028,21,1.625,0.095
20,806160108,47,1,56,2,2.0,3,3193.0,2517,676.0,1.831,1336,30,1.143,0.788
21,709327383,62,2,37,6,1.0,2,14470.0,1157,13313.0,0.966,1207,21,0.909,0.080

In [29]:
print(df['Age'].head(20))

0     45
1     49
3     40
5     44
6     51
7     32
8     37
9     48
10    42
11    65
12    56
13    35
14    57
15    44
16    48
17    41
18    61
19    45
20    47
21    62
Name: Age, dtype: int64

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10127 entries, 0 to 10128
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Customer_ID                     10127 non-null  int64
 1   Churn_Status                    10127 non-null  object
 2   Age                             10127 non-null  int64
 3   Gender                          10127 non-null  object
 4   Num_Dependents                  10127 non-null  int64
 5   Education_Level                 10127 non-null  object
 6   Marital_Status                  10127 non-null  object
 7   Income_Range                    10127 non-null  object
 8   Card_Type                       10127 non-null  object
 9   Tenure_Months                   10127 non-null  int64
 10  Num_Bank_Products               10127 non-null  int64
 11  Inactive_Months_Last_Year       10127 non-null  float64
 12  Customer_Service_Calls          10127 non-null  int64
 13  Credit_Limit                    10127 non-null  float64
 14  Revolving_Balance               10127 non-null  int64
 15  Available_Credit                10127 non-null  float64
 16  Spending_Change_Q4_Q1           10127 non-null  float64
 17  Total_Transaction_Amount        10127 non-null  int64
 18  Total_Transaction_Count         10127 non-null  int64
 19  Transaction_Count_Change_Q4_Q1  10127 non-null  float64
 20  Credit_Utilization_Ratio        10127 non-null  float64
dtypes: float64(6), int64(9), object(6)
memory usage: 1.7+ MB

In [31]:
df.to_csv("cleaned_merged_data.csv", index=False)